### ISSUE TITLE
Roadmap 中的“功能列表”和“开发计划”链接失效

### ISSUE THREAD

**Issue by wwfalcon** [goodrain/rainbond-docs#10]
[Roadmap](https://github.com/goodrain/rainbond-docs/blob/master/v3.6/architecture/roadmap.md) 中的“功能列表”和“开发计划”链接失效，对应代码位置为：

https://github.com/goodrain/rainbond-docs/blame/master/v3.6/architecture/roadmap.md#L7-L8

**Comment by zhouyq** [comment]
您看的是我们的文档源码，请参阅渲染后的页面：http://www.rainbond.com/docs/stable/architecture/roadmap.html

**Comment by wwfalcon** [comment]
参考下图访问流程：

![link](https://user-images.githubusercontent.com/72378/42995178-c1b2cfbc-8c42-11e8-834c-554ceed26011.png)

**Comment by zhouyq** [comment]
已经修正，感谢提醒

**Comment by wwfalcon** [comment]
不用客气 😄   你们的产品很值得关注
