### ISSUE TITLE
技术架构页面的 "组件部署架构文档" 404 了

### ISSUE THREAD

**Issue by GLYASAI** [goodrain/rainbond-docs#151]
[技术架构页面](https://www.rainbond.com/docs/architecture/architecture/) 最下面与个链接 `组件部署架构文档`, 地址是: https://www.rainbond.com/docs/architecture/operation-manual/component-description.html. 

这个地址是不存在的, 访问时返回 404

**Comment by Aaron-23** [comment]
Repaired
