### ISSUE TITLE
安装问题排查 Doc Update 

### ISSUE THREAD

**Issue by xsser** [goodrain/rainbond-docs#18]
Re: [安装问题排查](https://www.rainbond.com/docs//v3.7/operation-manual/trouble-shooting/install-issue.html)

## Issue Description
goroutine 1 [running]:
github.com/goodrain/rainbond/grctl/clients.InitClient(0x0, 0x0, 0xa, 0x0)
	/go/src/github.com/goodrain/rainbond/grctl/clients/kubernetes.go:43 +0x29f
github.com/goodrain/rainbond/grctl/cmd.Common(0xc4206a4c60)
	/go/src/github.com/goodrain/rainbond/grctl/cmd/cmd.go:70 +0xc7
github.com/goodrain/rainbond/grctl/cmd.NewCmdNode.func2(0xc4206a4c60, 0x0, 0xc4206a4c60)
	/go/src/github.com/goodrain/rainbond/grctl/cmd/node.go:233 +0x43
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.HandleAction(0x18ed240, 0x1c2a0b8, 0xc4206a4c60, 0xc42071ad00, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:502 +0xd4
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.Run(0x1b9e5f6, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1b9e5f6, 0x4, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:210 +0xb87
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420566fc0, 0xc4206a49a0, 0x0, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:383 +0xb28
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.startApp(0x1b9e682, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1bbc819, 0x18, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:298 +0x8fa
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.Command.Run(0x1b9e682, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1bbc819, 0x18, 0x0, ...)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/command.go:98 +0x1446
github.com/goodrain/rainbond/vendor/github.com/urfave/cli.(*App).Run(0xc420566e00, 0xc4200740c0, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/goodrain/rainbond/vendor/github.com/urfave/cli/app.go:259 +0x7b7
github.com/goodrain/rainbond/cmd/grctl/server.Run(0x17abeb9, 0x0)
	/go/src/github.com/goodrain/rainbond/cmd/grctl/server/grctl.go:46 +0x294
main.main()
	/go/src/github.com/goodrain/rainbond/cmd/grctl/grctl.go:33 +0x4c
**### panic: stat /root/.kube/config: no such file or directory**

**Comment by ysicing** [comment]
```
panic: stat /root/.kube/config: no such file or directory
```
k8s未安装,admin.kubeconfig文件未生成
