### ISSUE TITLE
V5.0版本升级指南 Doc Update 

### ISSUE THREAD

**Issue by herryliq** [goodrain/rainbond-docs#67]
Re: [V5.0版本升级指南](https://www.rainbond.com/docs//v5.0/operation-manual/how-to-update.html)

## Issue Description
没有写怎么升级

**Comment by barnettZQG** [comment]
@herryliq 
产品升级请关注 https://t.goodrain.com 相关升级贴，目前暂未在文档系统中更新。

**Comment by ysicing** [comment]
已经同步更新到文档 [V5.0版本升级指南](https://www.rainbond.com/docs/stable/operation-manual/how-to-update.html)
